# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Lanc.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1186, 757)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 70, 1141, 681))
        self.label.setStyleSheet("background-color: rgb(13, 0, 38);\n"
"border-radius:35px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(1020, 0, 131, 61))
        self.label_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:25px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 151, 591))
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(1090, 10, 41, 41))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("Images/icons8-close-window-48.png"))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.Start_pushButton = QtWidgets.QPushButton(Form)
        self.Start_pushButton.setGeometry(QtCore.QRect(60, 690, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Condensed")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Start_pushButton.setFont(font)
        self.Start_pushButton.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #000;\n"
"padding: 5px 10px;\n"
"background-color: #fff;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/icons8-circled-play-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start_pushButton.setIcon(icon)
        self.Start_pushButton.setIconSize(QtCore.QSize(35, 35))
        self.Start_pushButton.setObjectName("Start_pushButton")
        self.Stop_pushButton = QtWidgets.QPushButton(Form)
        self.Stop_pushButton.setGeometry(QtCore.QRect(1090, 10, 41, 41))
        self.Stop_pushButton.setStyleSheet("background-color: transparent;")
        self.Stop_pushButton.setText("")
        self.Stop_pushButton.setObjectName("Stop_pushButton")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(620, 90, 211, 51))
        self.label_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(1040, 10, 41, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Images/icons8-minimize-window-48.png"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(640, 100, 41, 41))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("Images/icons8-voice-48.png"))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(710, 100, 41, 41))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("Images/icons8-no-audio-40.png"))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(780, 100, 41, 41))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Images/icons8-voice-48.png"))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(640, 710, 491, 31))
        self.label_16.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:15px;")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.command_pushButton = QtWidgets.QPushButton(Form)
        self.command_pushButton.setGeometry(QtCore.QRect(650, 710, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.command_pushButton.setFont(font)
        self.command_pushButton.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"background-color: #000;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/icons8-plus-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.command_pushButton.setIcon(icon1)
        self.command_pushButton.setFlat(False)
        self.command_pushButton.setObjectName("command_pushButton")
        self.contact_pushButton_2 = QtWidgets.QPushButton(Form)
        self.contact_pushButton_2.setGeometry(QtCore.QRect(1010, 710, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.contact_pushButton_2.setFont(font)
        self.contact_pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"background-color: #000;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/icons8-contact-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contact_pushButton_2.setIcon(icon2)
        self.contact_pushButton_2.setObjectName("contact_pushButton_2")
        self.about_pushButton_3 = QtWidgets.QPushButton(Form)
        self.about_pushButton_3.setGeometry(QtCore.QRect(800, 710, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.about_pushButton_3.setFont(font)
        self.about_pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"background-color: #000;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Images/icons8-username-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_pushButton_3.setIcon(icon3)
        self.about_pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.about_pushButton_3.setObjectName("about_pushButton_3")
        self.more_pushButton_4 = QtWidgets.QPushButton(Form)
        self.more_pushButton_4.setGeometry(QtCore.QRect(910, 710, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.more_pushButton_4.setFont(font)
        self.more_pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"background-color: #000;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Images/icons8-info-48 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.more_pushButton_4.setIcon(icon4)
        self.more_pushButton_4.setObjectName("more_pushButton_4")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(390, 160, 701, 511))
        self.label_17.setStyleSheet("border-radius:30px;\n"
"background-color: rgb(13, 0, 38);")
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.gif1 = QtWidgets.QLabel(Form)
        self.gif1.setGeometry(QtCore.QRect(420, 200, 671, 421))
        self.gif1.setText("")
        self.gif1.setPixmap(QtGui.QPixmap("Images/Gif/AI-visualization-design-unscreen.gif"))
        self.gif1.setAlignment(QtCore.Qt.AlignCenter)
        self.gif1.setObjectName("gif1")
        self.volume_moins_push_button = QtWidgets.QPushButton(Form)
        self.volume_moins_push_button.setGeometry(QtCore.QRect(640, 90, 41, 41))
        self.volume_moins_push_button.setStyleSheet("background-color: transparent;")
        self.volume_moins_push_button.setText("")
        self.volume_moins_push_button.setObjectName("volume_moins_push_button")
        self.mute_push_button = QtWidgets.QPushButton(Form)
        self.mute_push_button.setGeometry(QtCore.QRect(710, 100, 41, 41))
        self.mute_push_button.setStyleSheet("background-color: transparent;")
        self.mute_push_button.setText("")
        self.mute_push_button.setObjectName("mute_push_button")
        self.Volume_plus_pushButton = QtWidgets.QPushButton(Form)
        self.Volume_plus_pushButton.setGeometry(QtCore.QRect(780, 100, 41, 41))
        self.Volume_plus_pushButton.setStyleSheet("background-color: transparent;")
        self.Volume_plus_pushButton.setText("")
        self.Volume_plus_pushButton.setObjectName("Volume_plus_pushButton")
        self.hide_pushButton = QtWidgets.QPushButton(Form)
        self.hide_pushButton.setGeometry(QtCore.QRect(1040, 10, 41, 41))
        self.hide_pushButton.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"}\n"
"")
        self.hide_pushButton.setText("")
        self.hide_pushButton.setObjectName("hide_pushButton")
        self.Facebook_pushButton = QtWidgets.QPushButton(Form)
        self.Facebook_pushButton.setGeometry(QtCore.QRect(50, 170, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Facebook_pushButton.setFont(font)
        self.Facebook_pushButton.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"    background-color: rgb(3, 155, 229);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Images/icons8-facebook-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Facebook_pushButton.setIcon(icon5)
        self.Facebook_pushButton.setIconSize(QtCore.QSize(45, 45))
        self.Facebook_pushButton.setObjectName("Facebook_pushButton")
        self.Youtube_pushButton_2 = QtWidgets.QPushButton(Form)
        self.Youtube_pushButton_2.setGeometry(QtCore.QRect(50, 240, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Youtube_pushButton_2.setFont(font)
        self.Youtube_pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"    background-color: rgb(234, 36, 52);\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Images/icons8-youtube-logo-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Youtube_pushButton_2.setIcon(icon6)
        self.Youtube_pushButton_2.setIconSize(QtCore.QSize(45, 45))
        self.Youtube_pushButton_2.setObjectName("Youtube_pushButton_2")
        self.Google_pushButton_3 = QtWidgets.QPushButton(Form)
        self.Google_pushButton_3.setGeometry(QtCore.QRect(50, 300, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Google_pushButton_3.setFont(font)
        self.Google_pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"background-color: #000;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Images/icons8-google-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Google_pushButton_3.setIcon(icon7)
        self.Google_pushButton_3.setIconSize(QtCore.QSize(45, 45))
        self.Google_pushButton_3.setObjectName("Google_pushButton_3")
        self.Tikitok_pushButton_4 = QtWidgets.QPushButton(Form)
        self.Tikitok_pushButton_4.setGeometry(QtCore.QRect(50, 360, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Tikitok_pushButton_4.setFont(font)
        self.Tikitok_pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #000;\n"
"padding: 5px 10px;\n"
"background-color: #fff;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Images/icons8-tiktok-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Tikitok_pushButton_4.setIcon(icon8)
        self.Tikitok_pushButton_4.setIconSize(QtCore.QSize(45, 45))
        self.Tikitok_pushButton_4.setObjectName("Tikitok_pushButton_4")
        self.Instagramm_pushButton_5 = QtWidgets.QPushButton(Form)
        self.Instagramm_pushButton_5.setGeometry(QtCore.QRect(50, 420, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Instagramm_pushButton_5.setFont(font)
        self.Instagramm_pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"color: #fff;\n"
"padding: 5px 10px;\n"
"background-color: #000;\n"
"border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Images/icons8-instagram-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Instagramm_pushButton_5.setIcon(icon9)
        self.Instagramm_pushButton_5.setIconSize(QtCore.QSize(45, 45))
        self.Instagramm_pushButton_5.setObjectName("Instagramm_pushButton_5")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(980, 100, 181, 101))
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:25;")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(990, 110, 51, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("Images/icons8-username-48.png"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.user_lineEdit = QtWidgets.QLineEdit(Form)
        self.user_lineEdit.setGeometry(QtCore.QRect(1040, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.user_lineEdit.setFont(font)
        self.user_lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.user_lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgb(0, 0, 0);\n"
"color:#fff;\n"
"border-radius:10px;\n"
"}")
        self.user_lineEdit.setText("")
        self.user_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.user_pushButton = QtWidgets.QPushButton(Form)
        self.user_pushButton.setGeometry(QtCore.QRect(1050, 160, 71, 31))
        self.user_pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 0);\n"
"color:#fff;\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(181, 181, 181);\n"
"\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Images/icons8-save-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_pushButton.setIcon(icon10)
        self.user_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.user_pushButton.setObjectName("user_pushButton")
        self.label_2.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_6.raise_()
        self.Start_pushButton.raise_()
        self.Stop_pushButton.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.command_pushButton.raise_()
        self.contact_pushButton_2.raise_()
        self.about_pushButton_3.raise_()
        self.more_pushButton_4.raise_()
        self.label_17.raise_()
        self.gif1.raise_()
        self.volume_moins_push_button.raise_()
        self.mute_push_button.raise_()
        self.Volume_plus_pushButton.raise_()
        self.hide_pushButton.raise_()
        self.Facebook_pushButton.raise_()
        self.Youtube_pushButton_2.raise_()
        self.Google_pushButton_3.raise_()
        self.Tikitok_pushButton_4.raise_()
        self.Instagramm_pushButton_5.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.user_lineEdit.raise_()
        self.user_pushButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Start_pushButton.setText(_translate("Form", "START"))
        self.command_pushButton.setText(_translate("Form", "Commande"))
        self.contact_pushButton_2.setText(_translate("Form", "Contacts"))
        self.about_pushButton_3.setText(_translate("Form", "About"))
        self.more_pushButton_4.setText(_translate("Form", "Mores"))
        self.Facebook_pushButton.setText(_translate("Form", "Facebook"))
        self.Youtube_pushButton_2.setText(_translate("Form", "Youtube"))
        self.Google_pushButton_3.setText(_translate("Form", "Google"))
        self.Tikitok_pushButton_4.setText(_translate("Form", "TikTok"))
        self.Instagramm_pushButton_5.setText(_translate("Form", "Insta"))
        self.user_lineEdit.setPlaceholderText(_translate("Form", "Utilisateur"))
        self.user_pushButton.setText(_translate("Form", "SAVE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
